make `SnowflakeRows` public
sigmacomputing/gosnowflake pull request #143
Opened 2023-06-07 23:25 UTC by madisonchamberlain

### Note
This will also need to be added to the safe branch once approved

### Why is this change being made
In the current multiplex code, rows.Inner() is used to peak into the rows of the specific driver. Since we still want to implement some specific behavior for snowflake (like the ability to get the queryID or monitoring data) we need a way to cast the rows to snowflake rows without using our forked SQL driver before we have time to build our own snowflake driver. Making this public will allow us to cast the rows to snowflake rows. 

### Description
`snowflakeRows` -> `SnowflakeRows`

### Checklist
- [ ] Code compiles correctly
- [ ] Run ``make fmt`` to fix inconsistent formats
- [ ] Run ``make lint`` to get lint errors and fix all of them
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary

2023-06-07 23:37 UTC, aldld requested changes
We normally expose functionality from gosnowflake internal structs by creating public interfaces and doing type assertions in Multiplex. Why won't that work for what you're trying to do? Renaming this thing everywhere is going to make rebasing harder, and leak implementation details into Multiplex.

2023-06-07 23:53 UTC, madisonchamberlain commented
> We normally expose functionality from gosnowflake internal structs by creating public interfaces and doing type assertions in Multiplex. Why won't that work for what you're trying to do? Renaming this thing everywhere is going to make rebasing harder, and leak implementation details into Multiplex.

Ok, I will make a public interface that exposes all of the same functions. I just thought this would be easier, but I hadn't considered the rebase issue

2023-06-07 23:54 UTC, closed without merging

2023-06-07 23:59 UTC, aldld commented
> > We normally expose functionality from gosnowflake internal structs by creating public interfaces and doing type assertions in Multiplex. Why won't that work for what you're trying to do? Renaming this thing everywhere is going to make rebasing harder, and leak implementation details into Multiplex.
> 
> Ok, I will make a public interface that exposes all of the same functions. I just thought this would be easier, but I hadn't considered the rebase issue

As a rule of thumb, we should strive to only make additive changes to gosnowflake (even better if they're in separate files), and avoid modifying the upstream code as much as possible.

2023-06-08 00:02 UTC, madisonchamberlain commented
> > > We normally expose functionality from gosnowflake internal structs by creating public interfaces and doing type assertions in Multiplex. Why won't that work for what you're trying to do? Renaming this thing everywhere is going to make rebasing harder, and leak implementation details into Multiplex.
> > 
> > 
> > Ok, I will make a public interface that exposes all of the same functions. I just thought this would be easier, but I hadn't considered the rebase issue
> 
> As a rule of thumb, we should strive to only make additive changes to gosnowflake (even better if they're in separate files), and avoid modifying the upstream code as much as possible.

Yeah thats a good rule of thumb